services:
  - type: web
    name: groupie-tracker
    env: go
    plan: free
    autoDeploy: true
    buildCommand: go build -o bin/server .
    startCommand: bin/server
    envVars:
      - key: PORT
        value: "8080"
        previewValue: "8080"
        generateValue: false
      # - key: DISCOGS_TOKEN
      #   value: ""
      #   previewValue: ""
      #   generateValue: false
